### ISSUE TITLE
Does this works with Udoo Neo? 

### ISSUE THREAD

**Issue by GonzaloCalandria** [smerkousdavid/Udoo-Library#4]
I can't make it work with udoo neo.
I did everything from the tutorial but every time I upload a sketch with some of the examples, the arduino doesn't work anymore and I need to run  `sudo rm /var/opt/m4/m3laft.fw` and restart the device so I can upload a working sketch (a simple led blinking for example).

**Comment by smerkousdavid** [comment]
@GonzaloCalandria this was originally designed by a naive me for the Udoo Duo/Quad, and could've theoretically worked on Neo, but I'm not sure. I can quickly whip up a more generic version for all serial devices to be able efficiently execute commands bi-directionally, as in interrupts on arduino side bind to code executes on python, have the same flexibility of networking over serial, and being able to control IO from python side.
